const routes = {
    home: '/',
    // profiles: '/profiles/@:id',
    profile: '/profile',
    search: '/search',
    laptop: '/laptop',
    brand: '/brand',
    cart: '/cart',
    login: '/login',
    info: '/info',
    // eslint-disable-next-line no-dupe-keys
    image: '/image',
    checkout: '/checkout',
    pdf: '/pdf',
    account: '/account',
    bill: '/bill',
    address: '/address',
    admin: '/admin',
    showroom: '/showroom',
    promotion: '/promotion',
    productList: '/admin/ProductList',
    newProduct: '/admin/ProductList/NewProduct',
    bannerList: '/admin/BannerList',
    newBannerList: '/admin/BannerList/newBanner',
    brandList: '/admin/BrandList',
    newBrandList: '/admin/BrandList/newBrand',
    bannerHorizonList: '/admin/BannerHorizon',
    newBannerHorizon: '/admin/BannerHorizon/newBannerHorizon',
    headerList: '/admin/HeaderList',
    newHeader: '/admin/HeaderList/newHeader',
    promotionList: '/admin/PromotionList',
    newPromotion: '/admin/PromotionList/newPromotion',
    carouselList: '/admin/CarouselList',
    newCarousel: '/admin/CarouselList/newCarousel',
    dashBoard: '/admin/Dashboard',
    showroomList: '/admin/ShowroomList',
    newShowroom: '/admin/ShowroomList/newShowroom',
    userList: '/admin/UserList',

    loading: '/loading',
};

export default routes;
