export const ALL_BANNER_HORIZONTAL_REQUEST = 'ALL_BANNER_HORIZONTAL_REQUEST';
export const ALL_BANNER_HORIZONTAL_SUCCESS = 'ALL_BANNER_HORIZONTAL_SUCCESS';
export const ALL_BANNER_HORIZONTAL_FAIL = 'ALL_BANNER_HORIZONTAL_FAIL';

export const MAIN_BANNER_HORIZONTAL_REQUEST = 'MAIN_BANNER_HORIZONTAL_REQUEST';
export const MAIN_BANNER_HORIZONTAL_SUCCESS = 'MAIN_BANNER_HORIZONTAL_SUCCESS';
export const MAIN_BANNER_HORIZONTAL_FAIL = 'MAIN_BANNER_HORIZONTAL_FAIL';

export const NEW_BANNER_HORIZONTAL_REQUEST = 'NEW_BANNER_HORIZONTAL_REQUEST';
export const NEW_BANNER_HORIZONTAL_SUCCESS = 'NEW_BANNER_HORIZONTAL_SUCCESS';
export const NEW_BANNER_HORIZONTAL_RESET = 'NEW_BANNER_HORIZONTAL_RESET';
export const NEW_BANNER_HORIZONTAL_FAIL = 'NEW_BANNER_HORIZONTAL_FAIL';

export const UPDATE_BANNER_HORIZONTAL_REQUEST = 'UPDATE_BANNER_HORIZONTAL_REQUEST';
export const UPDATE_BANNER_HORIZONTAL_SUCCESS = 'UPDATE_BANNER_HORIZONTAL_SUCCESS';
export const UPDATE_BANNER_HORIZONTAL_RESET = 'UPDATE_BANNER_HORIZONTAL_RESET';
export const UPDATE_BANNER_HORIZONTAL_FAIL = 'UPDATE_BANNER_HORIZONTAL_FAIL';

export const DELETE_BANNER_HORIZONTAL_REQUEST = 'DELETE_BANNER_HORIZONTAL_REQUEST';
export const DELETE_BANNER_HORIZONTAL_SUCCESS = 'DELETE_BANNER_HORIZONTAL_SUCCESS';
export const DELETE_BANNER_HORIZONTAL_RESET = 'DELETE_BANNER_HORIZONTAL_RESET';
export const DELETE_BANNER_HORIZONTAL_FAIL = 'DELETE_BANNER_HORIZONTAL_FAIL';

export const BANNER_HORIZONTAL_DETAILS_REQUEST = 'BANNER_HORIZONTAL_DETAILS_REQUEST';
export const BANNER_HORIZONTAL_DETAILS_SUCCESS = 'BANNER_HORIZONTAL_DETAILS_SUCCESS';
export const BANNER_HORIZONTAL_DETAILS_FAIL = 'BANNER_HORIZONTAL_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
