export const ALL_PROMOTION_SUCCESS = "ALL_PROMOTION_SUCCESS";
export const ALL_PROMOTION_REQUEST = "ALL_PROMOTION_REQUEST";
export const ALL_PROMOTION_FAIL = "ALL_PROMOTION_FAIL";

export const MAIN_PROMOTION_SUCCESS = "MAIN_PROMOTION_SUCCESS";
export const MAIN_PROMOTION_REQUEST = "MAIN_PROMOTION_REQUEST";
export const MAIN_PROMOTION_FAIL = "MAIN_PROMOTION_FAIL";

export const NEW_PROMOTION_REQUEST = "NEW_PROMOTION_REQUEST";
export const NEW_PROMOTION_SUCCESS = "NEW_PROMOTION_SUCCESS";
export const NEW_PROMOTION_RESET = "NEW_PROMOTION_RESET";
export const NEW_PROMOTION_FAIL = "NEW_PROMOTION_FAIL";

export const UPDATE_PROMOTION_REQUEST = "UPDATE_PROMOTION_REQUEST";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_RESET = "UPDATE_PROMOTION_RESET";
export const UPDATE_PROMOTION_FAIL = "UPDATE_PROMOTION_FAIL";

export const DELETE_PROMOTION_REQUEST = "DELETE_PROMOTION_REQUEST";
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS";
export const DELETE_PROMOTION_RESET = "DELETE_PROMOTION_RESET";
export const DELETE_PROMOTION_FAIL = "DELETE_PROMOTION_FAIL";

export const PROMOTION_DETAILS_REQUEST = "PROMOTION_DETAILS_REQUEST";
export const PROMOTION_DETAILS_SUCCESS = "PROMOTION_DETAILS_SUCCESS";
export const PROMOTION_DETAILS_FAIL = "PROMOTION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
