export const ALL_SHOWROOM_SUCCESS = "ALL_SHOWROOM_SUCCESS";
export const ALL_SHOWROOM_REQUEST = "ALL_SHOWROOM_REQUEST";
export const ALL_SHOWROOM_FAIL = "ALL_SHOWROOM_FAIL";

export const MAIN_SHOWROOM_SUCCESS = "MAIN_SHOWROOM_SUCCESS";
export const MAIN_SHOWROOM_REQUEST = "MAIN_SHOWROOM_REQUEST";
export const MAIN_SHOWROOM_FAIL = "MAIN_SHOWROOM_FAIL";

export const NEW_SHOWROOM_REQUEST = "NEW_SHOWROOM_REQUEST";
export const NEW_SHOWROOM_SUCCESS = "NEW_SHOWROOM_SUCCESS";
export const NEW_SHOWROOM_RESET = "NEW_SHOWROOM_RESET";
export const NEW_SHOWROOM_FAIL = "NEW_SHOWROOM_FAIL";

export const UPDATE_SHOWROOM_REQUEST = "UPDATE_SHOWROOM_REQUEST";
export const UPDATE_SHOWROOM_SUCCESS = "UPDATE_SHOWROOM_SUCCESS";
export const UPDATE_SHOWROOM_RESET = "UPDATE_SHOWROOM_RESET";
export const UPDATE_SHOWROOM_FAIL = "UPDATE_SHOWROOM_FAIL";

export const DELETE_SHOWROOM_REQUEST = "DELETE_SHOWROOM_REQUEST";
export const DELETE_SHOWROOM_SUCCESS = "DELETE_SHOWROOM_SUCCESS";
export const DELETE_SHOWROOM_RESET = "DELETE_SHOWROOM_RESET";
export const DELETE_SHOWROOM_FAIL = "DELETE_SHOWROOM_FAIL";

export const SHOWROOM_DETAILS_REQUEST = "SHOWROOM_DETAILS_REQUEST";
export const SHOWROOM_DETAILS_SUCCESS = "SHOWROOM_DETAILS_SUCCESS";
export const SHOWROOM_DETAILS_FAIL = "SHOWROOM_DETAILS_FAIL";

export const SHOWROOM_CITY_REQUEST = "SHOWROOM_CITY_REQUEST";
export const SHOWROOM_CITY_SUCCESS = "SHOWROOM_CITY_SUCCESS";
export const SHOWROOM_CITY_FAIL = "SHOWROOM_CITY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
